
version: "3.9"
services:
  app:
    build:
      context: ..
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paraplan
      SPRING_DATASOURCE_USERNAME: paraplan
      SPRING_DATASOURCE_PASSWORD: paraplan
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    container_name: paraplan-pg
    environment:
      POSTGRES_USER: paraplan
      POSTGRES_PASSWORD: paraplan
      POSTGRES_DB: paraplan
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ../para-plan-scenarios:/para-plan-scenarios:ro
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
               -c pg_stat_statements.max=10000
               -c pg_stat_statements.track=all
               -c track_io_timing=on
               -c random_page_cost=1.1
               -c effective_cache_size=2GB
               -c work_mem=64MB
